- name: variable on play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL= {{URL}}

#note: if we declare a variable on play level then we can access that variable in all tasks

- name: variable on file
  hosts: all
  vars_files:
    - sample-var.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{URL}}