- name: Setup catalogue
  ansible.builtin.copy:
    src: Nodejs.repo
    dest: /etc/yum.repos.d/Nodejs.repo

- name: Install Nodejs and gcc c++
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add user
  ansible.builtin.user:
    name: roboshop
    state: present

- name: download app code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: clean old app code
  ansible.builtin.file:
    path: /home/roboshop/catalogue/
    state: absent

- name: Copy app code
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: ye
  become_user: roboshop

- name: Install catalogue dependencies
  community.general.npm:
    path: /home/roboshop/catalogue/
  become_user: roboshop

- name: setup catalogue systemD config file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Start the catalogue
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    demon_reload: yes

